apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  name: azure-cluster-identity
  namespace: default
spec:
  type: ServicePrincipal
  tenantID: 33cab307-3f5a-4b91-a0d5-d681df820d94
  clientID: 073294e2-a100-43c5-8b06-a16ef779b9b7
  clientSecret:
    name: azure-cluster-identity
    namespace: default
  allowedNamespaces:
    list:
    - default
