apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: aks-workload-cluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedControlPlane
    name: aks-workload-cluster
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedCluster
    name: aks-workload-cluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedControlPlane
metadata:
  name: aks-workload-cluster
  namespace: default
spec:
  location: ${AZURE_LOCATION:-eastus}
  resourceGroupName: ${AZURE_RESOURCE_GROUP:-aks-cluster-rg}
  sshPublicKey: ""
  subscriptionID: ${AZURE_SUBSCRIPTION_ID}
  version: v1.29.2
  networkPolicy: azure
  networkPlugin: azure
  sku:
    tier: Standard
  identity:
    type: SystemAssigned
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: cluster-identity
  apiServerAccessProfile:
    enablePrivateCluster: false
  addonProfiles:
  - name: azureKeyvaultSecretsProvider
    enabled: true
  - name: azurepolicy
    enabled: true
  dnsServiceIP: 10.0.0.10
  serviceCidr: 10.0.0.0/16
  oidcIssuerProfile:
    enabled: true
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedCluster
metadata:
  name: aks-workload-cluster
  namespace: default
spec:
  subscriptionID: ${AZURE_SUBSCRIPTION_ID}
  resourceGroupName: ${AZURE_RESOURCE_GROUP:-aks-cluster-rg}
  location: ${AZURE_LOCATION:-eastus}
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: cluster-identity
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: agentpool0
  namespace: default
spec:
  clusterName: aks-workload-cluster
  replicas: 2
  template:
    spec:
      clusterName: aks-workload-cluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: agentpool0
      version: v1.29.2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: agentpool0
  namespace: default
spec:
  subscriptionID: ${AZURE_SUBSCRIPTION_ID}
  resourceGroupName: ${AZURE_RESOURCE_GROUP:-aks-cluster-rg}
  location: ${AZURE_LOCATION:-eastus}
  mode: System
  name: agentpool0
  sku: Standard_D2s_v3
  osDiskSizeGB: 128
  osDiskType: Managed
  osType: Linux
  enableNodePublicIP: false
  maxPods: 30
  availabilityZones:
  - "1"
  - "2"
  - "3"
  scaling:
    minSize: 1
    maxSize: 5
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: cluster-identity
