---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: aks-infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./capi-workload/infrastructure/aks-infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true

