---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: terraform
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./terraform-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: aks-infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./aks-infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
  dependsOn:
    - name: terraform
