---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: terraform-controller
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./capi-workload/infrastructure/terraform-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: terraform
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./capi-workload/infrastructure/terraform
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: terraform-controller
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: aks-infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./capi-workload/infrastructure/terraform-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: terraform
  wait: true

