---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: default
spec:
  controlPlaneRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: AzureASOManagedControlPlane
    name: ${CLUSTER_NAME}
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: AzureASOManagedCluster
    name: ${CLUSTER_NAME}

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureASOManagedControlPlane
metadata:
  name: ${CLUSTER_NAME}
  namespace: default
spec:
  resources:
  - apiVersion: containerservice.azure.com/v1api20240901
    kind: ManagedCluster
    metadata:
      annotations:
        serviceoperator.azure.com/credential-from: azure-cluster-identity
      name: ${CLUSTER_NAME}
    spec:
      dnsPrefix: ${CLUSTER_NAME}
      identity:
        type: SystemAssigned
      location: ${AZURE_LOCATION}
      networkProfile:
        networkPlugin: azure
      owner:
        name: ${AZURE_RESOURCE_GROUP_NAME}
      servicePrincipalProfile:
        clientId: msi
  version: ${KUBERNETES_VERSION}

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureASOManagedCluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: default
spec:
  resources:
  - apiVersion: resources.azure.com/v1api20200601
    kind: ResourceGroup
    metadata:
      annotations:
        serviceoperator.azure.com/credential-from: azure-cluster-identity
      name: ${AZURE_RESOURCE_GROUP_NAME}
    spec:
      location: ${AZURE_LOCATION}
      
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: ${CLUSTER_NAME}-pool0
  namespace: default
spec:
  clusterName: ${CLUSTER_NAME}
  replicas: ${WORKER_MACHINE_COUNT}
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: ${CLUSTER_NAME}
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: AzureASOManagedMachinePool
        name: ${CLUSTER_NAME}-pool0
      version: ${KUBERNETES_VERSION}

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureASOManagedMachinePool
metadata:
  name: ${CLUSTER_NAME}-pool0
  namespace: default
spec:
  resources:
  - apiVersion: containerservice.azure.com/v1api20240901
    kind: ManagedClustersAgentPool
    metadata:
      annotations:
        serviceoperator.azure.com/credential-from: azure-cluster-identity
      name: ${CLUSTER_NAME}-pool0
    spec:
      azureName: pool0
      mode: System
      owner:
        name: ${AZURE_RESOURCE_GROUP_NAME}
      type: VirtualMachineScaleSets
      vmSize: ${AZURE_NODE_MACHINE_TYPE}

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: ${CLUSTER_NAME}-pool1
  namespace: default
spec:
  clusterName: ${CLUSTER_NAME}
  replicas: ${WORKER_MACHINE_COUNT}
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: ${CLUSTER_NAME}
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: AzureASOManagedMachinePool
        name: ${CLUSTER_NAME}-pool1
      version: ${KUBERNETES_VERSION}

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureASOManagedMachinePool
metadata:
  name: ${CLUSTER_NAME}-pool1
  namespace: default
spec:
  resources:
  - apiVersion: containerservice.azure.com/v1api20240901
    kind: ManagedClustersAgentPool
    metadata:
      annotations:
        serviceoperator.azure.com/credential-from: azure-cluster-identity
      name: ${CLUSTER_NAME}-pool1
    spec:
      azureName: pool1
      mode: User
      owner:
        name: ${AZURE_RESOURCE_GROUP_NAME}
      type: VirtualMachineScaleSets
      vmSize: ${AZURE_NODE_MACHINE_TYPE}