apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: aks-infra
  namespace: flux-system
spec:
  approvePlan: auto
  interval: 5m
  path: ./terraform/
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  varsFrom:
    - kind: Secret
      name: azure-cluster-identity
      #     varsKeys:
      #       - subscriptionID:ARM_SUBSCRIPTION_ID
      #       - tenantID:ARM_TENANT_ID
      #       - clientID:ARM_CLIENT_ID
      #       - name: ARM_CLIENT_SECRET
      #         valueFrom:
      #           secretKeyRef:
      #             name: azure-cluster-identity-secret
      #             key: clientSecret
      #       - name: AZURE_LOCATION
      #         valueFrom:
      #           secretKeyRef:
      #             name: azure-cluster-identity-secret
      #             key: location
      #       - name: AZURE_RESOURCE_GROUP_NAME
      #         valueFrom:
      #           secretKeyRef:
      #             name: azure-cluster-identity-secret
      #             key: resourceGroupName
      #       - name: AZURE_SERVICE_PRINCIPAL_NAME
      #         valueFrom:
      #           secretKeyRef:
      #             name: azure-cluster-identity-secret
      #             key: servicePrincipalName
  # Terraform outputs will be written to the specified Kubernetes Secret,
  # allowing other resources to consume these outputs as needed.
  writeOutputsToSecret:
    name: terraform-outputs
  serviceAccountName: terraform-runner
