# NGINX Ingress Controller for AKS
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: default
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: default
spec:
  interval: 2m
  chart:
    spec:
      chart: ingress-nginx
      version: '4.13.x'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: default
  targetNamespace: default
  values:
    controller:
      service:
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
      metrics:
        enabled: true
      admissionWebhooks:
        enabled: true
    defaultBackend:
      enabled: true
      image:
        repository: ghcr.io/tarampampam/error-pages
        tag: 3.7.0
      extraEnvs:
        - name: TEMPLATE_NAME
          value: lost-in-space
        - name: SHOW_DETAILS
          value: "false"
      resources:
        requests:
          memory: 75Mi
          cpu: 50m
        limits:
          cpu: 50m
          memory: 75Mi
