---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-runner
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: terraform-runner
  namespace: flux-system
rules:
  # Read secrets for varsFrom (azure-cluster-identity, etc.)
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  # Create/update secrets for writeOutputsToSecret (terraform-outputs)
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: terraform-runner
  namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: terraform-runner
subjects:
  - kind: ServiceAccount
    name: terraform-runner
    namespace: flux-system
