apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: sample-app
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: flux
