apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/polarsquad/poc-capi-aks
  ref:
    branch: fluxcd-time
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./aks-workload
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
